FROM golang:1.18-alpine3.14 AS builder
 RUN apk update && apk add --no-cache git ca-certificates && update-ca-certificates
 WORKDIR /server
 
 # Create a user group 'xyzgroup'
 RUN addgroup -S emobgroup
 
 # Create a user 'appuser' under 'evrmsgroup'
 RUN adduser -S -D -h /server -u 1000 -G emobgroup appuser
 
 # Chown all the files to the app user.
 RUN chown -R appuser:emobgroup /server
 
 USER appuser
 
 ENV GO111MODULE=on
 
 COPY go.mod .
 COPY go.sum .
 
 RUN go mod download
 #RUN swagger version
 
 COPY . .
 
 RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -buildvcs=false -mod=readonly -a -installsuffix cgo -o /go/bin/emob-dms
 
 FROM centos:8
 COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
 COPY --from=builder /go/bin/emob-dms /go/bin/emob-dms
 
 EXPOSE 8080
 ENTRYPOINT ["/go/bin/emob-dms"]